//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Scover.WinClean.Resources {
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Logs {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logs() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Scover.WinClean.Resources.Logs", typeof(Logs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creating restore point....
        /// </summary>
        public static string CreatingRestorePoint {
            get {
                return ResourceManager.GetString("CreatingRestorePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exiting the application..
        /// </summary>
        public static string Exiting {
            get {
                return ResourceManager.GetString("Exiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A filesystem error occured while attempting to access script &quot;{0}&quot;..
        /// </summary>
        public static string FileSystemErrorAcessingScript {
            get {
                return ResourceManager.GetString("FileSystemErrorAcessingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Script file &quot;{0}&quot; has invalid or missing data..
        /// </summary>
        public static string InvalidScriptData {
            get {
                return ResourceManager.GetString("InvalidScriptData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notepad opened..
        /// </summary>
        public static string NotepadOpened {
            get {
                return ResourceManager.GetString("NotepadOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rebooting for application maintenance....
        /// </summary>
        public static string RebootingForAppMaintenance {
            get {
                return ResourceManager.GetString("RebootingForAppMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restore point created successfully..
        /// </summary>
        public static string RestorePointCreated {
            get {
                return ResourceManager.GetString("RestorePointCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error during restore point creation: {0}.
        /// </summary>
        public static string RestorePointCreationError {
            get {
                return ResourceManager.GetString("RestorePointCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Script &quot;{0}&quot; deleted..
        /// </summary>
        public static string ScriptDeleted {
            get {
                return ResourceManager.GetString("ScriptDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Script &quot;{0}&quot; executed..
        /// </summary>
        public static string ScriptExecuted {
            get {
                return ResourceManager.GetString("ScriptExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Script execution canceled..
        /// </summary>
        public static string ScriptExecutionCanceled {
            get {
                return ResourceManager.GetString("ScriptExecutionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Script(s) executed sucessfully..
        /// </summary>
        public static string ScriptsExecuted {
            get {
                return ResourceManager.GetString("ScriptsExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} script(s) loaded..
        /// </summary>
        public static string ScriptsLoaded {
            get {
                return ResourceManager.GetString("ScriptsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The application started..
        /// </summary>
        public static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Starting the execution of {0} script(s)....
        /// </summary>
        public static string StartingExecutionOfScripts {
            get {
                return ResourceManager.GetString("StartingExecutionOfScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An unhandled exception occured: {0}.
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
    }
}
