//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scover.WinClean.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScriptMetadata {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptMetadata() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scover.WinClean.Resources.ScriptMetadata", typeof(ScriptMetadata).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Categories&gt;
        ///  &lt;Category&gt;
        ///    &lt;Name&gt;Maintenance&lt;/Name&gt;
        ///    &lt;Name xml:lang=&quot;fr&quot;&gt;Maintenance&lt;/Name&gt;
        ///    &lt;Description&gt;Maintenance scripts that are recommended to run regularly. Windows performs maintenance actions periodically, but doing it manually ensures maximum efficiency. These scripts improve system performance and extend hardware life expectancy.&lt;/Description&gt;
        ///    &lt;Description xml:lang=&quot;fr&quot;&gt;Scripts de maintenance dont l&apos;excécution régulière est recommandée.  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Impacts&gt;
        ///  &lt;Impact&gt;
        ///    &lt;Name&gt;Ergonomics&lt;/Name&gt;
        ///    &lt;Name xml:lang=&quot;fr&quot;&gt;Ergonomie&lt;/Name&gt;
        ///    &lt;Description&gt;Improves system practicality, comfort and ease of use.&lt;/Description&gt;
        ///    &lt;Description xml:lang=&quot;fr&quot;&gt;Améliore la fonctionnalité du système, son confort et sa facilité d&apos;utilisation.&lt;/Description&gt;
        ///  &lt;/Impact&gt;
        ///  &lt;Impact&gt;
        ///    &lt;Name&gt;Free storage space&lt;/Name&gt;
        ///    &lt;Name xml:lang=&quot;fr&quot;&gt;Espace de stockage libre&lt;/Name&gt;
        ///    &lt;Description&gt;Frees up disk space.&lt;/Descr [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Impacts {
            get {
                return ResourceManager.GetString("Impacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;RecommendationLevels&gt;
        ///  &lt;RecommendationLevel Color=&quot;Green&quot;&gt;
        ///    &lt;Name&gt;Yes&lt;/Name&gt;
        ///    &lt;Name xml:lang=&quot;fr&quot;&gt;Oui&lt;/Name&gt;
        ///    &lt;Description&gt;This script is for any user. It won&apos;t hinder common Windows features.&lt;/Description&gt;
        ///    &lt;Description xml:lang=&quot;fr&quot;&gt;Ce script est destiné n&apos;importe quel utilisateur. Il n&apos;entravera aucune fonctionnalité Windows commune.&lt;/Description&gt;
        ///  &lt;/RecommendationLevel&gt;
        ///  &lt;RecommendationLevel Color=&quot;Gray&quot;&gt;
        ///    &lt;Name&gt;Limited&lt;/Name&gt;
        ///    &lt;Nam [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string RecommendationLevels {
            get {
                return ResourceManager.GetString("RecommendationLevels", resourceCulture);
            }
        }
    }
}
