//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scover.WinClean.Resources.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScriptExecution {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptExecution() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scover.WinClean.Resources.UI.ScriptExecution", typeof(ScriptExecution).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating restore point....
        /// </summary>
        public static string CreatingRestorePointContent {
            get {
                return ResourceManager.GetString("CreatingRestorePointContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} scripts executed.
        ///To finish the operation, it is recommended to restart the system..
        /// </summary>
        public static string ExecutionCompletedContent {
            get {
                return ResourceManager.GetString("ExecutionCompletedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning completed.
        /// </summary>
        public static string ExecutionCompletedMainInstruction {
            get {
                return ResourceManager.GetString("ExecutionCompletedMainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation may take some time..
        /// </summary>
        public static string ExecutionProgressContent {
            get {
                return ResourceManager.GetString("ExecutionProgressContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} out of {1} scripts executed ({2} remaining)
        ///Currently executing: {3}
        ///Time remaining: {4}.
        /// </summary>
        public static string ExecutionProgressExpanderText {
            get {
                return ResourceManager.GetString("ExecutionProgressExpanderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing the scripts....
        /// </summary>
        public static string ExecutionProgressMainInstruction {
            get {
                return ResourceManager.GetString("ExecutionProgressMainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically restart when finished.
        /// </summary>
        public static string ExecutionProgressVerificationText {
            get {
                return ResourceManager.GetString("ExecutionProgressVerificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script &quot;{0}&quot; has been running for {1} and is probably hung..
        /// </summary>
        public static string HungScriptDialogContent {
            get {
                return ResourceManager.GetString("HungScriptDialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Script execution.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
