//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scover.WinClean.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Logs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scover.WinClean.Resources.Logs", typeof(Logs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared logs folder..
        /// </summary>
        public static string ClearedLogsFolder {
            get {
                return ResourceManager.GetString("ClearedLogsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating restore point....
        /// </summary>
        public static string CreatingRestorePoint {
            get {
                return ResourceManager.GetString("CreatingRestorePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting the application..
        /// </summary>
        public static string Exiting {
            get {
                return ResourceManager.GetString("Exiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete log file: {0}.
        /// </summary>
        public static string FailedToDeleteLogFile {
            get {
                return ResourceManager.GetString("FailedToDeleteLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load custom script &apos;{0}&apos; due to a filesystem error: {1}.
        /// </summary>
        public static string FSErrorLoadingCustomScript {
            get {
                return ResourceManager.GetString("FSErrorLoadingCustomScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script &apos;{0}&apos; has been executing for {1} and is probably hung..
        /// </summary>
        public static string HungScript {
            get {
                return ResourceManager.GetString("HungScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hung script &apos;{0}&apos; terminated..
        /// </summary>
        public static string HungScriptTerminated {
            get {
                return ResourceManager.GetString("HungScriptTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script file &apos;{0}&apos; has invalid or missing data..
        /// </summary>
        public static string InvalidScriptData {
            get {
                return ResourceManager.GetString("InvalidScriptData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebooting for application maintenance....
        /// </summary>
        public static string RebootingForAppMaintenance {
            get {
                return ResourceManager.GetString("RebootingForAppMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore point created successfully..
        /// </summary>
        public static string RestorePointCreated {
            get {
                return ResourceManager.GetString("RestorePointCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during restore point creation: {0}.
        /// </summary>
        public static string RestorePointCreationError {
            get {
                return ResourceManager.GetString("RestorePointCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script &apos;{0}&apos; deleted..
        /// </summary>
        public static string ScriptDeleted {
            get {
                return ResourceManager.GetString("ScriptDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script &apos;{0}&apos; executing....
        /// </summary>
        public static string ScriptExecuting {
            get {
                return ResourceManager.GetString("ScriptExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script execution canceled..
        /// </summary>
        public static string ScriptExecutionCanceled {
            get {
                return ResourceManager.GetString("ScriptExecutionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script(s) executed sucessfully..
        /// </summary>
        public static string ScriptsExecuted {
            get {
                return ResourceManager.GetString("ScriptsExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripts saved..
        /// </summary>
        public static string ScriptsSaved {
            get {
                return ResourceManager.GetString("ScriptsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved..
        /// </summary>
        public static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the execution of {0} script(s)....
        /// </summary>
        public static string StartingExecutionOfScripts {
            get {
                return ResourceManager.GetString("StartingExecutionOfScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System restore was enabled for all eligible drives to create a restore point..
        /// </summary>
        public static string SystemRestoreEnabled {
            get {
                return ResourceManager.GetString("SystemRestoreEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occured: {0}.
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
    }
}
