//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scover.WinClean.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    public sealed partial class PersistentSettings : global::System.Configuration.ApplicationSettingsBase {
        private static PersistentSettings defaultInstance = ((PersistentSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PersistentSettings())));
        
        public static PersistentSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Scover.WinClean.DataAccess.SerializableStringDictionary ScriptExecutionTimes {
            get {
                return ((global::Scover.WinClean.DataAccess.SerializableStringDictionary)(this["ScriptExecutionTimes"]));
            }
        }
    }
}
